### ISSUE TITLE
Since 32bit App indicator Version came out, my Banking Auth App stopped working

### ISSUE THREAD

**Issue by mexx42** [Divested-Mobile/DivestOS-Build#123]
Hi There,

well, i am not sure if this is the right place to ask such a question, but i havent found a better place - if i am wrong here, please tell me where i can ask my question !

i am using divestos on a one plus nord for a couple of months now and am very happy with it - so thanks a lot for the amazing work !

currently i am running build QQ3A.200805.001 Android 10 DivestOS 17.1

i think it was two update cycles in the past where the "32bit App Indicator" appeared the first time when my banking auth app stopped working ... it opens and immediately closes.

here is what adb logcat says when i start the app:

```06-09 13:32:58.206   996  1028 I ActivityManager: Start proc 14874:at.erstebank.securityapp/u0a237 for pre-top-activity {at.erstebank.securityapp/at.erstebank.securityapp.MainActivity}
06-09 13:32:58.227 14874 14874 E ank.securityap: Not starting debugger since process cannot load the jdwp agent.
06-09 13:32:58.239 11468 11468 W kworker/0:0: type=1400 audit(0.0:2540018): avc: denied { syslog } for capability=34 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability2 permissive=0
06-09 13:32:58.239 11468 11468 W kworker/0:0: type=1400 audit(0.0:2540019): avc: denied { sys_admin } for capability=21 scontext=u:r:kernel:s0 tcontext=u:r:kernel:s0 tclass=capability permissive=0
06-09 13:32:58.267 14874 14874 I MultiDex: VM with version 2.1.0 has multidex support
06-09 13:32:58.267 14874 14874 I MultiDex: Installing application
06-09 13:32:58.267 14874 14874 I MultiDex: VM has multidex support, MultiDex support library is disabled.
06-09 13:32:58.270 14874 14874 W ComponentDiscovery: Class com.google.firebase.dynamicloading.DynamicLoadingRegistrar is not an found.
06-09 13:32:58.271 14874 14874 I FirebaseApp: Device unlocked: initializing all Firebase APIs for app [DEFAULT]
06-09 13:32:58.274 14874 14874 I FirebaseInitProvider: FirebaseApp initialization successful
06-09 13:32:58.284 14874 14902 E FirebaseInstanceId: Google Play services missing or without correct permission.
06-09 13:32:58.325   996  1016 D ConnectivityService: requestNetwork for uid/pid:10237/14874 NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ]
06-09 13:32:58.325   996  1872 D UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ] with score 60 and serial -1
06-09 13:32:58.326   996  1930 D Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ] with score 60 and serial -1
06-09 13:32:58.328 14874 14874 W GooglePlayServicesUtil: at.erstebank.securityapp requires the Google Play Store, but it is missing.
06-09 13:32:58.328   996  1872 D WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ] with score 60 and serial -1
06-09 13:32:58.328  2111  2111 D PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ] with score 60 and serial -1
06-09 13:32:58.332 14874 14912 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-09 13:32:58.332   996  1017 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
06-09 13:32:58.334   668 14913 E ResolverController: No valid NAT64 prefix (117, <unspecified>/0)
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: QUALCOMM build                   : a4f08a5, I3f9a96e91d
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Build Date                       : 05/11/20
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.29.00.07
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Local Branch                     : 
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r89-rel
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Remote Branch                    : NONE
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Build Config                     : S P 8.0.12 AArch64
06-09 13:32:58.339 14874 14905 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-09 13:32:58.345 14874 14905 I AdrenoGLES-0: PFP: 0x016dd087, ME: 0x00000000
06-09 13:32:58.408   996  1026 I ActivityTaskManager: Displayed at.erstebank.securityapp/.MainActivity: +264ms
06-09 13:32:58.439 14920 14920 D AST     :  $20882 
06-09 13:32:58.440 14920 14920 D AST     :  $20908 
06-09 13:32:58.440 14920 14920 D AST     :  $20913 
06-09 13:32:58.441 14920 14925 D AST     :  $20994 
06-09 13:32:58.441 14920 14920 D AST     :  $20754 Operation not permitted $20755 1
06-09 13:32:58.442 14920 14920 D AST     :  $20759 
06-09 13:32:58.456   669   669 I Zygote  : Process 14874 exited due to signal 9 (Killed)
06-09 13:32:58.485   996  1849 W InputDispatcher: channel 'cd0c943 at.erstebank.securityapp/at.erstebank.securityapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
06-09 13:32:58.485   996  1849 E InputDispatcher: channel 'cd0c943 at.erstebank.securityapp/at.erstebank.securityapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
06-09 13:32:58.485   996  1016 I WindowManager: WIN DEATH: Window{cd0c943 u0 at.erstebank.securityapp/at.erstebank.securityapp.MainActivity}
06-09 13:32:58.485   996  1016 W InputDispatcher: Attempted to unregister already unregistered input channel 'cd0c943 at.erstebank.securityapp/at.erstebank.securityapp.MainActivity (server)'
06-09 13:32:58.486   996  4127 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=2625, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND Uid: 10237] ], android.os.BinderProxy@6d0c631)
06-09 13:32:58.486   996 13743 D ConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ], android.os.BinderProxy@e2d8116)
06-09 13:32:58.486   996  4025 I ActivityManager: Process at.erstebank.securityapp (pid 14874) has died: fore TOP 
06-09 13:32:58.486   996  1029 I libprocessgroup: Successfully killed process cgroup uid 10237 pid 14874 in 0ms
06-09 13:32:58.488   996  1878 D ConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=2624, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10237] ] (release request)
06-09 13:32:58.496  1952  1952 D ImageWallpaper: wallpaper visibility changes to: false
06-09 13:32:58.501   912   912 E Layer   : [Surface(name=AppWindowToken{459706f token=Token{2de74e ActivityRecord{d468249 u0 com.android.launcher3/.lineage.LineageLauncher t1018}}})/@0xd5d4f24 - animation-leash#0] No local sync point found
06-09 13:32:58.501   912   912 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 1 line
06-09 13:32:58.501   912   912 E Layer   : [Surface(name=AppWindowToken{459706f token=Token{2de74e ActivityRecord{d468249 u0 com.android.launcher3/.lineage.LineageLauncher t1018}}})/@0xd5d4f24 - animation-leash#0] No local sync point found
06-09 13:32:58.501   912   912 E Layer   : [Surface(name=AppWindowToken{a32b4b7 token=Token{89befb6 ActivityRecord{58f4b51 u0 at.erstebank.securityapp/.MainActivity t1109}}})/@0x7b8abcb - animation-leash#0] No local sync point found
06-09 13:32:58.507   996  4025 W ActivityTaskManager: Force removing ActivityRecord{58f4b51 u0 at.erstebank.securityapp/.MainActivity t1109}: app died, no saved state
06-09 13:32:58.526   996  1021 W ActivityManager: setHasOverlayUi called on unknown pid: 14874
06-09 13:32:58.540   996  1016 D WindowManager: relayoutVisibleWindow: Window{45c0b3 u0 com.android.launcher3/com.android.launcher3.lineage.LineageLauncher EXITING} mAnimatingExit=true, mRemoveOnExit=false, mDestroying=false
06-09 13:32:58.501   912   912 I chatty  : uid=1000(system) /system/bin/surfaceflinger identical 1 line
06-09 13:32:58.501   912   912 E Layer   : [Surface(name=AppWindowToken{a32b4b7 token=Token{89befb6 ActivityRecord{58f4b51 u0 at.erstebank.securityapp/.MainActivity t1109}}})/@0x7b8abcb - animation-leash#0] No local sync point found
06-09 13:32:58.567  1952  1952 D ImageWallpaper: wallpaper visibility changes to: true
06-09 13:32:58.899  2111  2245 W hw-Parcel: **** enforceInterface() expected 'vendor.qti.hardware.radio.qtiradio@2.1::IQtiRadioIndication' but read 'vendor.qti.hardware.radio.qtiradio@2.0::IQtiRadioIndication'
06-09 13:32:58.899  2111  2245 W System.err: java.lang.SecurityException: HWBinder invocation to an incorrect interface
06-09 13:32:58.899  2111  2245 W System.err: 	at android.os.HwParcel.enforceInterface(Native Method)
06-09 13:32:58.900  2111  2245 W System.err: 	at vendor.qti.hardware.radio.qtiradio.V2_2.IQtiRadioIndication$Stub.onTransact(IQtiRadioIndication.java:651)
06-09 13:32:58.900  2111  2245 E android_os_HwBinder: Uncaught exception!
```
suspicious to me looks: 

```
06-09 13:32:58.284 14874 14902 E FirebaseInstanceId: Google Play services missing or without correct permission.

06-09 13:32:58.328 14874 14874 W GooglePlayServicesUtil: at.erstebank.securityapp requires the Google Play Store, but it is missing.
```

what can i do ?
can i go back to an older version of divestos ?

thanks & regards,
marcus.

**Comment by SkewedZeppelin** [comment]
Please go to Settings > Security and ensure the `Enable native code debugging` toggle is checked/enabled.
Then try the banking app again.

**Comment by mexx42** [comment]
Thanks, it works only when i enable "native code debugging" ... can you please explain why ?

**Comment by SkewedZeppelin** [comment]
Some (bank) apps ptrace themself as a rudimentary form of anti-tamper.
They'll fail if they can't.

That settings disables ptrace.

**Comment by mexx42** [comment]
Oh, thanks !
