### ISSUE TITLE
Unable to launch seedvault's restore activity on secondary user profile

### ISSUE THREAD

**Issue by oaymn** [Divested-Mobile/DivestOS-Build#138]
**Device info :**

- DivestOS version : 19.1
- Device model: Xiaomi POCO X3 Pro - Vayu
- Seedvault version : 12-3.0

Here are the options I tried :
 
**Dialer codes :**

Trying to trigger a full system restore using `*#*#7378673#*#*`/`*#*#RESTORE#*#*` as described in the Seedvault [FAQ](https://github.com/seedvault-app/seedvault/wiki/FAQ#how-to-restore-after-passing-through-setup-wizard) did not work on the secondary user, instead it launched the UI on the primary user.

**ADB Shell :**

Trying to start the restore activity from the shell using the command `adb shell am start-activity -a com.stevesoltys.seedvault.RESTORE_BACKUP` failed throwing the following exception :

```java
Starting: Intent { act=com.stevesoltys.seedvault.RESTORE_BACKUP }

Exception occurred while executing 'start-activity':
java.lang.SecurityException: Permission Denial: starting Intent { act=com.stevesoltys.seedvault.RESTORE_BACKUP flg=0x10000000 cmp=com.stevesoltys.seedvault/.restore.RestoreActivity } from null (pid=15340, uid=2000) requires com.stevesoltys.seedvault.RESTORE_BACKUP
	at com.android.server.wm.ActivityTaskSupervisor.checkStartAnyActivityPermission(ActivityTaskSupervisor.java:1059)
	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:983)
	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:672)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1252)
	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1224)
	at com.android.server.am.ActivityManagerService.startActivityAsUserWithFeature(ActivityManagerService.java:2952)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:572)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:201)
	at com.android.modules.utils.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:97)
	at android.os.ShellCommand.exec(ShellCommand.java:38)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:8656)
	at android.os.Binder.shellCommand(Binder.java:950)
	at android.os.Binder.onTransact(Binder.java:834)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:5167)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2519)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
```

**Activity Launcher app :**

Trying to launch the restore activity using the [Activity Launcher app](https://github.com/butzist/ActivityLauncher) also failed, the logs are provided below (not sure if it helps):

```ruby
07-21 22:40:10.087  1334  9572 W ActivityTaskManager: Permission Denial: starting Intent { flg=0x14000000 cmp=com.stevesoltys.seedvault/.restore.RestoreActivity } from ProcessRecord{62f317c 16421:de.szalkowski.activitylauncher/u0a154} (pid=16421, uid=10154) requires com.stevesoltys.seedvault.RESTORE_BACKUP
07-21 22:40:10.088 16421 16421 W System.err: java.lang.SecurityException: Permission Denial: starting Intent { flg=0x14000000 cmp=com.stevesoltys.seedvault/.restore.RestoreActivity } from ProcessRecord{62f317c 16421:de.szalkowski.activitylauncher/u0a154} (pid=16421, uid=10154) requires com.stevesoltys.seedvault.RESTORE_BACKUP`
```

I have opened the same [issue](https://github.com/seedvault-app/seedvault/issues/428#issue-1313939843) at the seedvault repo, and one of the devs believes it's a ROM integration issue.

Any thoughts?

**Comment by SkewedZeppelin** [comment]
I haven't made any changes to the implementation, so it is likely broken in upstream LineageOS too.

I think I remember GrapheneOS mentioning changes necessary for it to work.
I skimmed through the CalyxOS Gerrit and didn't find any relevant changes.

**Comment by oaymn** [comment]
The **Activity launcher app** method was working back in 2021 for grapheneos according to this [comment](https://github.com/seedvault-app/seedvault/issues/208#issuecomment-779117173), but I don't know if it's still the case now.

The user from the comment [documented](https://hub.libranet.de/wiki/graphene-os/wiki/Backups) the backup and restore process for secondary user and work profiles, and seeing from the restore section it seems the **ADB shell** method was another alternative solution but no longer works.

I'll close this for now since it doesn't seem to be a DivestOS issue.
