### ISSUE TITLE
Bluetooth cannot be enabled on Nexus 5X (bullhead)

### ISSUE THREAD

**Issue by acozzette** [Divested-Mobile/DivestOS-Build#175]
I just installed the `15.1-20221213-dos-bullhead` build, and found that nothing happens when I try to enable bluetooth. Whenever I try it, I see something like this in the logs:

```
12-18 11:53:37.188  2604  2614 D BluetoothManagerService: enable(com.android.settings):  mBluetooth =null mBinding = false mState = OFF
12-18 11:53:37.188  2604  2626 D BluetoothManagerService: MESSAGE_ENABLE(0): mBluetooth = null
12-18 11:53:37.188  2604  2614 D BluetoothManagerService: enable returning
12-18 11:53:37.211  5514  5514 E SELinux : seapp_context_lookup:  No match for app with uid 1002, seinfo default, name com.android.bluetooth
12-18 11:53:37.211  5514  5514 E SELinux : selinux_android_setcontext:  Error setting context for app with uid 1002, seinfo default:targetSdkVersion=27:complete: No such file or directory
12-18 11:53:37.211  5514  5514 E Zygote  : selinux_android_setcontext(1002, 0, "default:targetSdkVersion=27:complete", "com.android.bluetooth") failed
12-18 11:53:37.211  5514  5514 F zygote64: jni_internal.cc:675] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:652: selinux_android_setcontext failed
12-18 11:53:37.214  2604  2626 I ActivityManager: Start proc 5514:com.android.bluetooth/1002 for service com.android.bluetooth/.btservice.AdapterService
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] Runtime aborting...
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] Dumping all threads without appropriate locks held: thread list lock mutator lock
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] All threads:
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] DALVIK THREADS (1):
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] "main" prio=5 tid=1 Runnable
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | group="" sCount=0 dsCount=0 flags=0 obj=0x741df5f0 self=0x7c0c6bea00
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | sysTid=2178 nice=0 cgrp=default sched=0/0 handle=0x7c9136d9a8
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | stack=0x7fe222d000-0x7fe222f000 stackSize=8MB
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | held mutexes= "abort lock" "mutator lock"(shared held)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   kernel: (couldn't read /proc/self/task/2178/stack)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   native: (backtrace::Unwind failed for thread 2178: Thread doesn't exist)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:105)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:222)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:174)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] 
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] Aborting thread:
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] "main" prio=5 tid=1 Native
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | group="" sCount=0 dsCount=0 flags=0 obj=0x741df5f0 self=0x7c0c6bea00
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | sysTid=2178 nice=0 cgrp=default sched=0/0 handle=0x7c9136d9a8
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | state=? schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | stack=0x7fe222d000-0x7fe222f000 stackSize=8MB
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   | held mutexes= "abort lock"
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   kernel: (couldn't read /proc/self/task/2178/stack)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   native: (backtrace::Unwind failed for thread 2178: Thread doesn't exist)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native method)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.Zygote.forkAndSpecialize(Zygote.java:105)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.ZygoteConnection.processOneCommand(ZygoteConnection.java:222)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.ZygoteServer.runSelectLoop(ZygoteServer.java:174)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:796)
12-18 11:53:37.277  5514  5514 F zygote64: runtime.cc:523] 
12-18 11:53:37.277  5514  5514 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 5514 (main), pid 5514 (main)
12-18 11:53:37.309  5521  5521 F crash_dump64: crash_dump.cpp:298] failed to attach to thread 5514: Operation not permitted
12-18 11:53:37.310  2255  2255 I /system/bin/tombstoned: received crash request for pid 5514
12-18 11:53:37.312  5514  5514 F libc    : crash_dump helper failed to exec
12-18 11:53:37.312  2255  2255 W /system/bin/tombstoned: crash socket received short read of length 0 (expected 12)
12-18 11:53:37.313  2604  2624 I BootReceiver: Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
12-18 11:53:37.320   438   438 D SurfaceFlinger: duplicate layer name: changing com.android.settings/com.android.settings.bluetooth.RequestPermissionActivity to com.android.settings/com.android.settings.bluetooth.RequestPermissionActivity#1
12-18 11:53:37.325  2178  2178 I Zygote  : Process 5514 exited due to signal (6)
12-18 11:53:37.379  4800  5324 D OpenGLRenderer: endAllActiveAnimators on 0x7be9912c00 (RippleDrawable) with handle 0x7be962a240
12-18 11:53:38.108  2604  2856 D WificondControl: Scan result ready event
12-18 11:53:40.191  2604  2626 E BluetoothManagerService: MESSAGE_TIMEOUT_BIND
12-18 11:53:42.435  2604  2629 E LightsService: Light requested not available on this device. 2
12-18 11:53:47.217  2604  2618 W ActivityManager: Process ProcessRecord{89394a1 5514:com.android.bluetooth/1002} failed to attach
12-18 11:53:47.218  2604  2618 W ActivityManager: Forcing bringing down service: ServiceRecord{3a586c6 u0 com.android.bluetooth/.btservice.AdapterService}
12-18 11:53:47.218  2604  2618 I ActivityManager: Killing 5514:com.android.bluetooth/1002 (adj -10000): start timeout
12-18 11:53:47.219  2604  2620 W zygote64: kill(-5514, 9) failed: No such process
12-18 11:53:47.219  2604  2620 I zygote64: Successfully killed process cgroup uid 1002 pid 5514 in 0ms
12-18 11:53:47.325  2604  2856 I ActivityManager: Killing 4532:com.simplemobiletools.gallery.pro/u0a63 (adj 906): empty #17
12-18 11:53:47.327  2604  2620 W zygote64: kill(-4532, 9) failed: No such process
12-18 11:53:47.360  2604  2620 I chatty  : uid=1000(system) ActivityManager identical 1 line
12-18 11:53:47.405  2604  2620 W zygote64: kill(-4532, 9) failed: No such process
12-18 11:53:47.432  4800  4800 E WindowManager: 
12-18 11:53:47.432  4800  4800 E WindowManager: android.view.WindowLeaked: Activity com.android.settings.bluetooth.RequestPermissionActivity has leaked window DecorView@a527dca[] that was originally added here
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:485)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.Dialog.show(Dialog.java:330)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at com.android.settings.bluetooth.RequestPermissionActivity.createDialog(RequestPermissionActivity.java:196)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at com.android.settings.bluetooth.RequestPermissionActivity.onActivityResult(RequestPermissionActivity.java:216)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.Activity.dispatchActivityResult(Activity.java:7276)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.os.Looper.loop(Looper.java:164)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at java.lang.reflect.Method.invoke(Native Method)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-18 11:53:47.432  4800  4800 E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-18 11:53:47.438  2604  2620 W zygote64: kill(-4532, 9) failed: No such process
12-18 11:53:47.438  2604  2620 I zygote64: Successfully killed process cgroup uid 10063 pid 4532 in 111ms
12-18 11:53:47.439  2604  2627 W ActivityManager: setHasOverlayUi called on unknown pid: 4532
```

It looks to me like perhaps SELinux is preventing bluetooth from being turned on.

**Comment by SkewedZeppelin** [comment]
Bluetooth works just fine on my bullhead.

Is this your first install? or did you update from a previous version?

**Comment by acozzette** [comment]
This is my first install (before this I was using LineageOS).

Sorry for not mentioning before, but I did get the confirmation dialog and clicked "allow". But after that, bluetooth stayed off and I got the logcat error above. I get what appears to be the same error if I try to toggle bluetooth on in the settings app.

**Comment by SkewedZeppelin** [comment]
You probably do not have correct firmware.
I'd recommend flashing the latest firmware partitions manually.

Download this, extract it: https://dl.google.com/dl/android/aosp/bullhead-opm7.181205.001-factory-5f189d84.zip

fastboot flash each of these: https://gitlab.com/divested-mobile/firmware-empty/-/blob/master/0SHA512SUMS#L92-105
```
9845bcd1bb301c210601e841a4d532c56043608024f85a36e9a33be6f5eeb5b5e2  bullhead/aboot.img
2b1bdd748bb2a5b4b5d23cbe0c11e5f1158b3b9f57f2505a791a0f08c6026d740b3f47ca284649ef3d52f961d15fbc76a0a6a0e97418ab0b09ee2d5314748220  bullhead/bootloader.img
953eec78fdf282779c457c7032ad923ffd6e4873736697fbe2ee60ca864284807ce48750657e0caeaa9f02806cad4760ec938e284fb43a8c2c46a6ecef523d8b  bullhead/cmnlib.img
8509550aff4cb40cc34c44985e8eddf36f9e72495407552a4c1ae0c4de9ca75e239cd0b657e9ab5100717fbbe6af17657645cc9fabe1fc6822dfca933d4cad73  bullhead/hyp.img
0f6172ab6425b1e547822bb0960d152d1365d4243ba61d0b4b1fe025fcdf01fe8d50dd39fac426f0894768d785e6c660d4cca6b099c7ff3510cc799c5d3b44e9  bullhead/imgdata.img
c1094f1b17f01f3f7bd86b8bd8f57666d5732518ef807a5d953324abc0bf5dda503aafb98ecc4942f547b4d4bfdd5ed1892a2fffe286c1db94ff7b574aaa1b85  bullhead/keymaster.img
bedda56a602622c265a39fc6407d29825b1373ec41c5125936c8edfcad8bba79ed2f0bb2bda254bec8819eab9a561c84a162d612f1dbd371e4b6c235dffcb31b  bullhead/pmic.img
cfbff47b3cfd4822de1a4244aee58d97b6fcda176724c49bb55daf07b50a384b6d7a1dd1d95e6b984da37e8535da118ccee1bca6198b668010ce21dd79d50d93  bullhead/radio.img
722caf316802f441a522794f68096acda2a1f9336159a2b8b66a430803dc38f232d0d23f8619b62d1beab2eaeea8a01c610c22077b7cd44279c49ce4988abb4c  bullhead/rpm.img
e6171da105c7e1f8fc041647f2747b434b2a5846d11593a006307ff0f2c271519040d9e1134a683101f1dd241b980aa4e2b5fddc473b0be6d56cf601c4e7257a  bullhead/sbl1.img
7c108b469b74c0ff944105b7ab37674de20f46d43fde483b161d0e4c5116bf5256a71760b06297064a8e2f7bb5f96330bc350f320060e3a1d605f272b2f8d9a5  bullhead/sdi.img
7191fe3c456554aa6ffc3234f74d9ec09d6362bd62ff209b6354f00637e47aabc8ab261ef72414a6e3142bcf8d0a6a04021cea6561db3b8f206bfae3c1531c3a  bullhead/sec.img
e55504524abff906fb7dcd343a99868c063b9bba636c8f85c19c84b2a63dda2d41667458e13f9044e39468c8e47e0836e09bba77198adad0d740a1bb81d8b7a2  bullhead/tz.img
3ff0362ab94d75ae5b3a59163afca908afe8bb1be2b45842be61cb5ca75d6b434824993e3fc9262429a0d4bf73ebbef98c1c74a4ac34e5717d6a288a92e79de7  bullhead/vendor.img

```

**Comment by acozzette** [comment]
I gave that a try and `flash-bash.sh` appeared to successfully write the bootloader and radio images, but unfortunately I'm still getting the same problem when I try to turn on bluetooth.

**Comment by SkewedZeppelin** [comment]
Can you verify that Bluetooth works on another OS, such as stock or razorlove's unofficial LineageOS builds? https://forum.xda-developers.com/t/rom-unofficial-lineageos-15-1-for-nexus-5x-bullhead.3724575/

**Comment by acozzette** [comment]
Yes, I was actually using razorloves' unofficial build (the one released in March 2022) until yesterday and can confirm that bluetooth was working.

**Comment by SkewedZeppelin** [comment]
Had you flashed DivestOS on top of LineageOS without wiping userdata?

**Comment by acozzette** [comment]
I did install the DivestOS recovery and used that to install DivestOS. I'm not sure which step you mean by wiping userdata, but I did the factory reset in the recovery after the `adb sideload` step.

The only area where I really deviated from the instructions [here](https://divestos.org/index.php?page=bootloader#fastbootUnlocking) is that I skipped the `fastboot oem unlock`, since my bootloader was already unlocked. Is that part important since it has the side effect of wiping the device?

**Comment by SkewedZeppelin** [comment]
> did the factory reset in the recovery after the adb sideload step.

that is what I meant

> deviated from the instructions [here](https://divestos.org/index.php?page=bootloader#fastbootUnlocking) is that I skipped the fastboot oem unlock

nah, that shouldn't matter

just very strange that my bullhead works and yours doesn't.

**Comment by acozzette** [comment]
Yeah, that is strange. I wonder if I should build with selinux disabled just to see whether that fixes it.

**Comment by SkewedZeppelin** [comment]
You don't need permissive to see denials:
`adb logcat -b all -d | grep -i audit`
