### ISSUE TITLE
Pixel 2 XL (taimen) "Wallpaper & style" bugs

### ISSUE THREAD

**Issue by Yaanu** [Divested-Mobile/DivestOS-Build#188]
When using "Wallpaper & style" on the Pixel 2 XL (taimen, DivestOS version 20-20230213-dos-taimen), some significant bugs occur which cause it to crash after almost any operation, including:

- Changing the home or lock screen wallpaper
- Changing the accent colors
- Setting "Dark theme" on or off

Furthermore, whenever the wallpaper is set as a device default, the preview display functions as normal, but using a custom wallpaper causes the previews to glitch; one is considered corrupted and the other remains the device default.

The following is the crash log shared by the OS when the standard pop-up appears:
```
type: crash
osVersion: google/lineage_taimen/taimen:13/TQ1A.230205.002/eng.emy.20230213.113449:user/release-keys
package: com.android.wallpaper:33
process: com.android.wallpaper
 
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
	at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:348)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:148)
	at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:128)
	at com.bumptech.glide.Glide.with(Glide.java:801)
	at com.android.wallpaper.asset.CurrentWallpaperAssetVN.loadDrawable(CurrentWallpaperAssetVN.java:132)
	at com.android.wallpaper.asset.Asset.lambda$loadPreviewImage$1$com-android-wallpaper-asset-Asset(Asset.java:301)
	at com.android.wallpaper.asset.Asset$$ExternalSyntheticLambda1.onDimensionsDecoded(Unknown Source:13)
	at com.android.wallpaper.asset.StreamableAsset.lambda$decodeRawDimensions$1(StreamableAsset.java:128)
	at com.android.wallpaper.asset.StreamableAsset$$ExternalSyntheticLambda4.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
 
```

**Comment by SkewedZeppelin** [comment]
Did you recently upgrade from 19.1? If so this is a known once-off bug:
> `Wallpapers & Styles` app may crash after upgrading to 20.0 from 19.1, clear it's app data to fix.

**Comment by Yaanu** [comment]
I installed DivestOS 20 only a few weeks ago, without upgrading. I did try clearing the app data to see what would happen, but that did nothing. I also tried rebooting just in case, but that didn't work either.
I'm not sure how to activate/deactivate exec-spawning, unless that's a different way of saying "secure app spawning". I tried turning that off, rebooting, and clearing the app data, but that also did nothing.

**Comment by SkewedZeppelin** [comment]
If you revoke storage permission from the app, are you able to use everything else?

I wonder if you maybe have some corrupt/invalid image it tries to parse.

**Comment by Yaanu** [comment]
When I cleared the app data before, the permissions were revoked. Everything else seemed to work, but turning the permissions back on came up with the same problems.

However, I did actually manage to fix the issue just now, and permissions seem to have a role in it! It seems that "Wallpapers & style" is not an app made for Android 13, and so the permissions for "Photos and videos" and "Music and audio" are normally tied together. However, when enabling permissions through the app itself, it only enables "Photos and videos" without enabling "Music and audio". When I enabled the latter through App Info options, everything started working as intended, and the app no longer crashed.

Attached below are screenshots of the permissions page (as it was before I had fixed it) and the two pop-ups that appear when manually enabling or disabling the permissions.

![Screenshot_20230218-205556_Permission controller](https://user-images.githubusercontent.com/2125527/219909666-5638b366-4595-4a91-80b9-4b5b0e0f3eb8.png)
![Screenshot_20230218-205614_Permission controller-1](https://user-images.githubusercontent.com/2125527/219909771-acf4b17a-8caa-44d4-8094-80f7e81e5260.png)
![Screenshot_20230218-205641_Permission controller-1](https://user-images.githubusercontent.com/2125527/219909775-fd56942b-998d-4be7-b4ce-61b131834e62.png)

**Comment by SkewedZeppelin** [comment]
Oh wow, that is very interesting and it fixes the preview issue too!

**Comment by Yaanu** [comment]
Yeah, it would seem that enabling both "Photos" and "Music" permissions are what fix the issue with the app. The stock Android 13 app only seems to request "Photos and videos", so it might be something to do with DivestOS itself and how it builds the app.

Whatever the case, I'm glad to have figured out what the hassle was all about.
