### ISSUE TITLE
App "Garmin connect" crashes with error related to CompanionDeviceManager

### ISSUE THREAD

**Issue by cmonty14** [Divested-Mobile/DivestOS-Build#196]
After installing DivestOS 20.0 on my device and installing all previously used apps I have identified this issue:
I cannot pair my Garmin watch with app "[Garmin connect](https://connect.garmin.com/)".

The issue is that "Garmin connect" crashes when it starts pairing process after watch has been identified. Here's the relevant crash information:
```
type: crash
osVersion: OnePlus/OnePlus5T/OnePlus5T:13/TQ2A.230305.008.C1/eng.emy.20230321.233403:user/release-keys
package: com.garmin.android.apps.connectmobile:7558
process: com.garmin.android.apps.connectmobile

android.content.ActivityNotFoundException: No Activity found to handle null
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
at android.app.Activity.startIntentSenderForResultInner(Activity.java:5895)
at android.app.Activity.startIntentSenderForResult(Activity.java:5858)
at androidx.activity.ComponentActivity.startIntentSenderForResult(SourceFile:2)
at android.app.Activity.startIntentSenderForResult(Activity.java:5813)
at androidx.activity.ComponentActivity.startIntentSenderForResult(SourceFile:1)
at com.garmin.android.apps.connectmobile.bic.SetupWizardActivity$q.onDeviceFound(SourceFile:41)
at android.companion.CompanionDeviceManager$Callback.onAssociationPending(CompanionDeviceManager.java:252)
at android.companion.CompanionDeviceManager$AssociationRequestCallbackProxy$$ExternalSyntheticLambda0.accept(Unknown Source:4)
at android.companion.CompanionDeviceManager$AssociationRequestCallbackProxy.lambda$execute$1(CompanionDeviceManager.java:924)
at android.companion.CompanionDeviceManager$AssociationRequestCallbackProxy$$ExternalSyntheticLambda4.run(Unknown Source:4)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:48)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

I could pair the watch in > Settings > Bluetooth, but then the watch is not identified by "Garmin connect" either.
And according to Garmin this is not the pairing process to be used.

Could you please provide a fix for this issue?

**Comment by cmonty14** [comment]
Can you confirm that this fix will be available with next release?
If yes, how can I apply the fix before this release?

**Comment by SkewedZeppelin** [comment]
> Can you confirm that this fix will be available with next release?

The change has already been made and tested.

> If yes, how can I apply the fix before this release?

You can't without recompiling the system

**Comment by SkewedZeppelin** [comment]
Available in https://divestos.org/pages/news#2023-04
