### ISSUE TITLE
org.lineageos.recorder android.content.ActivityNotFoundException Pixel 2XL

### ISSUE THREAD

**Issue by webenhanced** [Divested-Mobile/DivestOS-Build#252]
Hi folks,
Flashed divested-20.0-20230830-dos-taimen(-fastboot) onto a Pixel 2XL as per the website instruction. All went well including locking the bootloader.

Opened the inbuilt "Recorder" app and recorded two test messages of 8 or 9 seconds.

Tap the "music note" icon and I see the recording in the list. But when I tap on a recording, it just goes back to the record screen. When I keep trying, eventually I get a message saying that "Recorder keeps stopping".

Here's the crash info displayed on screen after pushing "show details":
```
type: crash
osVersion: google/lineage_taimen/taimen:13/TQ3A.230805.001/eng.emy.20230830.143812:user/release-keys
package: org.lineageos.recorder:33
process: org.lineageos.recorder

android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=content://media/... typ=audio/* flg=0x10000001 }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2200)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1839)
	at android.app.Activity.startActivityForResult(Activity.java:5507)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:689)
	at android.app.Activity.startActivityForResult(Activity.java:5465)
	at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:670)
	at android.app.Activity.startActivity(Activity.java:5963)
	at android.app.Activity.startActivity(Activity.java:5930)
	at org.lineageos.recorder.ListActivity.onPlay(ListActivity.java:116)
	at org.lineageos.recorder.list.RecordingsAdapter.lambda$onCreateViewHolder$0(RecordingsAdapter.java:66)
	at org.lineageos.recorder.list.RecordingsAdapter.$r8$lambda$F6c35trpQazLTpvAGhXf9AAVHdM(Unknown Source:0)
	at org.lineageos.recorder.list.RecordingsAdapter$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7542)
	at android.view.View.performClickInternal(View.java:7519)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29476)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```
Is there some permission I haven't set? Or is this a bug?
thanks, graham

**Comment by SkewedZeppelin** [comment]
You need to install some sort of music/media player as one is not included.
There are recommendations here in the Media section: https://divestos.org/pages/recommended_apps

**Comment by webenhanced** [comment]
Ah, glad it is something simple. Thanks for the quick response.

**Comment by webenhanced** [comment]
Just had to add the Recordings directory into the library scan. I tested Vanilla and Auxio. Both work. Think I prefer Vanilla at this stage.

thanks for your help.

**Comment by SkewedZeppelin** [comment]
Glad you got it working! :)
